### ISSUE TITLE
License evaluation

### ISSUE THREAD

**Issue by phax** [unimaze/unimaze-peppol-stylesheets#18]
Hi guys,
very nice job, but due to the existing GPL 3 license, I have doubts to use them in my software that is Apache 2 licensed.
Maybe you could consider changing the license to Apache 2, MIT, FreedBSD or Mozilla Public Licene?
What's important to me is, that the license is not viral, and compatible to my license (Apache 2)
Thanks, Philip

**Comment by phax** [comment]
Hi Markus,
any update on this one?
Thx

**Comment by svanteschubert** [comment]
Same here, it would be nice to use your open-source work freely in any environment, even for commercial software. :-)

Would you accept a patch, changing the license? 

Thanks in advance,
Svante

**Comment by svanteschubert** [comment]
I first saw this old issue! You did it! :D Using Apache Licence is great! Thanks for making your work freely available! 

Kind regards,
Svante

**Comment by phax** [comment]
It was already done
